spring.application.name=easyll
app.scores.file-path=./data/scores/scores.csv
app.scores.write-path=./data/scores/scores.csv
app.accounts.file-path=./data/users/users.csv
app.match.max-attempts=30
app.match.board-size=5
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN
app.dictionaries.root-path=./data/dictionaries
app.dictionaries.primary-language-code=hun
app.dictionaries.modes=flashcards,match
