spring.application.name=easyll
app.scores.file-path=./scores.csv
app.scores.write-path=./scores.csv
app.words.source=classpath:data/dictionary.csv
app.match.max-attempts=30
app.match.board-size=5
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN
